version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: WARNING
    formatter: standard
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: standard
    filename: logs/bot.log
    maxBytes: 10485760
    backupCount: 5
    encoding: utf-8
root:
  level: INFO
  handlers: [console, file]
loggers:
  asyncio:
    level: WARNING
  urllib3:
    level: WARNING
  websockets.client:
    level: WARNING
  websockets.protocol:
    level: WARNING
